Featuremilestone3 branch
em-em-D/React-calculator pull request #3
Opened 2020-09-04 16:31 UTC by em-em-D

Milestone3 requirement is have been implemented fully
As in my previous code review, Linter is still not working on my repository, having a slight linting error

2020-09-04 21:51 UTC, Forison requested changes
## Status:: Changes Required❌.
# 🙋‍♂️ Michael
#### You have done a good job on this one, here are a few issues we have to address before the project could be approved🤗 .
* [ ] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
- You have not followed all the steps for setting up your linters as stated in the requirement, kindly visit this [page](https://github.com/microverseinc/linters-config/tree/master/react-redux), take note of step one. Let us address these issues once and for all.
### That is it kindly address the issue and submit a re-review👨‍🔧.
#### Happy coding👨‍💻
Addo Forison

2020-09-08 08:21 UTC, em-em-D commented
Hi have followed all the instructions on the linter repository but still to no avail, linter is still not working, I have tried to fix it for the past 3 days now and hasn't worked, I have moved on to milestone 4

2020-09-08 14:56 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @em-em-D :hand: 
Great job on this milestone so far :clap: . We only need to make a small change before moving on. 

- [ ] We need to improve your README file with relevant information about your project.
![Screenshot from 2020-09-08 11-59-54](https://user-images.githubusercontent.com/30977845/92493435-e374ec80-f1ca-11ea-9bb8-87e2f2814d50.png)

- [ ] Microverse has switched from the stickler (stickler.ci) to Github actions as it described [here](https://microverse.zendesk.com/hc/en-us/articles/360049654493-June-4th-2020-GitHub-Actions-is-replacing-Stickler). We need to apply that change to your project :smile: . The Github Actions instructions can be found [here](https://github.com/microverseinc/linters-config/tree/master/react-redux)
You can safely delete the `.stickler` files

- [ ] After switch the linter solution to Github Actions we need to make sure that all tests pass.

Please kindly submit for code review again after making these changes.
Feel free to message me on slack if you have any questions :smile: 
Happy Coding :computer: 
**Sergio Torres**

2020-09-10 19:15 UTC, bellom requested changes
## Hi @em-em-D  :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**Kindly check out my comments below;**

**let's keep it simple, kindly work on the following;**
**The previous reviewer already mentioned this;**

### 1. 
**Let's make your repo looks professional by applying all the 3 basic rules, kindly update your `README` file and remove unnecessary content**.
Checkout out the below link for help, free free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright

![image](https://user-images.githubusercontent.com/31897434/92685488-b4c45680-f32f-11ea-9bea-222a21c096a6.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

### 2.
 **NOTE:** Microverse has moved on to Github actions for continuous deployment please use that instead of a stickler. 
![image](https://user-images.githubusercontent.com/31897434/85197008-14353c00-b2d6-11ea-932b-d3a0ab291c2a.png)

https://github.com/microverseinc/linters-config/tree/master/javascript


**I'm pretty sure after these 2 things, you will get your PR approval! 😄** 


### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-09-14 10:32 UTC, em-em-D commented
hello, sean bellom,
I Have set up what is required except that linters are not working on my project for some time now,
and secondly what do you mean by dedicated repository and professional, is my repo not professional? if you think so then contact microverse to change their guidelines cause it the guidelines they have provided that have been followed,
please I have done my best for 2 weeks now

2020-09-14 10:55 UTC, bellom commented
Hi @em-em-D, 

Apparently you have tried to fix the linter's problem, understandable.
Let's keep it simple;
1. You should not push the `node_modules` file to the repo.
2. Let's set up the Github Action 👉  https://github.com/microverseinc/linters-config/tree/master/react-redux


Don't get me wrong, your repo looks good, but we need to make it look better by updating your `README`, seems you didn't check the README template I shared above, if you do you will know that your README file looks good but there is still a lot of room for improvement.

2020-09-15 18:41 UTC, em-em-D commented
I have tried and tried and tried to fix eslint but to no avail if you can fix it kindly do, I have moved on to the next milestone

2020-09-15 19:57 UTC, bellom commented
> I have tried and tried and tried to fix eslint but to no avail if you can fix it kindly do, I have moved on to the next milestone

Yeah, it's obvious you have been trying hard on it, it is understandable to move to the next milestone but before that, we could sync on a call to look into it together because I think the rest of the milestone might be having linter's issue too.

2020-09-15 20:53 UTC, uryelah requested changes
Hi **Michael Damulak**, I'm Sarah your reviewer for this PR 👩‍🚀 

I know you must be tired of the linting checks by now but let's revisit them again because you have actually made progress since the initial issue.

The linters are set and the GitHub actions are working, the thing now is that your code is not passing all of the code standards and style checks from eslint.

If you click in the failing checks for details you'll be able to see the problematic lines and which rules they are breaking as seen in the screenshots below:

![Screenshot_2020-09-15 Featuremilestone3 branch by em-em-D · Pull Request #3 · em-em-D React-calculator](https://user-images.githubusercontent.com/16193212/93263084-a1741980-f77b-11ea-91a6-f0ec17a609c5.png)
![Screenshot_2020-09-15 Featuremilestone3 branch by em-em-D · Pull Request #3 · em-em-D React-calculator(1)](https://user-images.githubusercontent.com/16193212/93263085-a2a54680-f77b-11ea-8ac0-67341900e35a.png)

You'll be able to see the same issue sin your terminal at the root of your project directory.

Just use the CLI commands found at: [https://eslint.org/docs/user-guide/command-line-interface](https://eslint.org/docs/user-guide/command-line-interface);

For the errors at the ServiceWorker, this file is not really needed for this project, so you can just delete it, while making sure it's not being imported anywhere. 
The other issues you can check one by one and fix them, some of them you can even fix automatically if you use the eslint command for that.

Again, check the [eslint command's documentation ](https://eslint.org/docs/user-guide/command-line-interface)and fix the linting issues. Those should be noted in all your milestones so the earlier you fix them the better. Also, make sure you always check for linting issues before pushing your code and opening a PR.

Rock on! 🎸 👨‍🎤 

# Required Changes 🏗️ 🐛 💡

- [ ] Make sure the linter checks don't output any error or warning.

(Check the comments below for the other fixes)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-09-15 20:53 UTC, uryelah commented on src/App.js
> +import React from 'react';
- [ ] Please remove unused files, you are using the components/App.js file, not this one in index.js.
Please remove it so you don't have two App.js files in your repo.

2020-09-15 20:53 UTC, uryelah commented on src/components/App.js
> +        <div className="button">
- [ ] [OPTIONAL] Give the class name 'button' a more descriptive name like button-container or even just buttons.

2020-09-15 20:53 UTC, uryelah commented on src/components/Button.js
> +  const classes = `${color} ${wide ? 'fifty-percent' : 'twenty-five-percent'}`.trim();
- [ ] Independent of the color the button should also have a border property in CSS.

2020-09-15 20:53 UTC, uryelah commented on src/components/ButtonPanel.js
> +      <Button handleClick={handleClick} color="light-gray" name="AC" />
- [ ] [OPTIONAL] Think on a way to repeat less code, the <Button> element em specific, you can try adding a loop to make the code drier.

2020-09-15 20:53 UTC, uryelah commented on README.md
> +Milestone 3 React Calculator
- [ ] [OPTIONAL] I'd strongly encourage you to update your README file to the template linked by my colegues, the reason for that is that you'll most likelly have to do that in the future in career/interview prep and that a better README file can make recruiters more prone to contact you about jobs and opportunities.

2020-09-15 21:05 UTC, em-em-D commented
Hi Sarah,
Thanks for the code review but there is nothing you are saying that hasn’t
been done or tried. The service file is needed because you can’t run “npm
start” without it, it would trow and error, and when eslint is installed
locally to adjust styling errors  npm start doesn’t work.
All have been tried . I suggest you try it on your local machine as and see
if it works. Cheers

On Tue, Sep 15, 2020 at 9:53 PM Sarah Chamorro <notifications@github.com>
wrote:

> *@uryelah* requested changes on this pull request.
>
> Hi *Michael Damulak*, I'm Sarah your reviewer for this PR 👩‍🚀
>
> I know you must be tired of the linting checks by now but let's revisit
> them again because you have actually made progress since the initial issue.
>
> The linters are set and the GitHub actions are working, the thing now is
> that your code is not passing all of the code standards and style checks
> from eslint.
>
> If you click in the failing checks for details you'll be able to see the
> problematic lines and which rules they are breaking as seen in the
> screenshots below:
>
> [image: Screenshot_2020-09-15 Featuremilestone3 branch by em-em-D · Pull
> Request #3 · em-em-D React-calculator]
> <https://user-images.githubusercontent.com/16193212/93263084-a1741980-f77b-11ea-91a6-f0ec17a609c5.png>
> [image: Screenshot_2020-09-15 Featuremilestone3 branch by em-em-D · Pull
> Request #3 · em-em-D React-calculator(1)]
> <https://user-images.githubusercontent.com/16193212/93263085-a2a54680-f77b-11ea-8ac0-67341900e35a.png>
>
> You'll be able to see the same issue sin your terminal at the root of your
> project directory.
>
> Just use the CLI commands found at:
> https://eslint.org/docs/user-guide/command-line-interface;
>
> For the errors at the ServiceWorker, this file is not really needed for
> this project, so you can just delete it, while making sure it's not being
> imported anywhere.
> The other issues you can check one by one and fix them, some of them you
> can even fix automatically if you use the eslint command for that.
>
> Again, check the eslint command's documentation
> <https://eslint.org/docs/user-guide/command-line-interface>and fix the
> linting issues. Those should be noted in all your milestones so the earlier
> you fix them the better. Also, make sure you always check for linting
> issues before pushing your code and opening a PR.
>
> Rock on! 🎸 👨‍🎤
> Required Changes 🏗️ 🐛 💡
>
>    - Make sure the linter checks don't output any error or warning.
>
> (Check the comments below for the other fixes)
> ------------------------------
>
> *Kindly fix the pointed out issues and comments below before requesting
> the next code review*
> ------------------------------
>
> Cheers and Happy coding!👏👏👏
>
> Code review by *Sarah Uryelah Silva Chamorro*
>
> (Feel free to contact me on slack by the handle of *sarah* if you have
> any additional question)
> ------------------------------
>
> In src/App.js
> <https://github.com/em-em-D/React-calculator/pull/3#discussion_r488955878>
> :
>
> > @@ -0,0 +1,29 @@
>
> +import React from 'react';
>
>
>
>    - Please remove unused files, you are using the components/App.js
>    file, not this one in index.js.
>    Please remove it so you don't have two App.js files in your repo.
>
> ------------------------------
>
> In src/components/App.js
> <https://github.com/em-em-D/React-calculator/pull/3#discussion_r488959632>
> :
>
> > @@ -0,0 +1,22 @@
>
> +import React, { Component } from 'react';
>
> +import Display from './Display';
>
> +import ButtonPanel from './ButtonPanel';
>
> +import './App.css';
>
> +
>
> +class App extends Component {
>
> +  render() {
>
> +    return (
>
> +      <div className="box">
>
> +        <div className="display">
>
> +          <Display />
>
> +        </div>
>
> +        <div className="button">
>
>
>
>    - [OPTIONAL] Give the class name 'button' a more descriptive name like
>    button-container or even just buttons.
>
> ------------------------------
>
> In src/components/Button.js
> <https://github.com/em-em-D/React-calculator/pull/3#discussion_r488959997>
> :
>
> > @@ -0,0 +1,29 @@
>
> +import React from 'react';
>
> +import PropTypes from 'prop-types';
>
> +
>
> +const Button = ({
>
> +  wide, color, name, handleClick,
>
> +}) => {
>
> +  const classes = `${color} ${wide ? 'fifty-percent' : 'twenty-five-percent'}`.trim();
>
>
>
>    - Independent of the color the button should also have a border
>    property in CSS.
>
> ------------------------------
>
> In src/components/ButtonPanel.js
> <https://github.com/em-em-D/React-calculator/pull/3#discussion_r488960766>
> :
>
> > @@ -0,0 +1,47 @@
>
> +import React from 'react';
>
> +import PropTypes from 'prop-types';
>
> +import Button from './Button';
>
> +import './ButtonPanel.css';
>
> +import './button.css';
>
> +
>
> +const ButtonPanel = ({ handleClick }) => (
>
> +
>
> +  <div className="panel">
>
> +
>
> +    <div className="group">
>
> +      <Button handleClick={handleClick} color="light-gray" name="AC" />
>
>
>
>    - [OPTIONAL] Think on a way to repeat less code, the element em
>    specific, you can try adding a loop to make the code drier.
>
> ------------------------------
>
> In README.md
> <https://github.com/em-em-D/React-calculator/pull/3#discussion_r488961884>
> :
>
> > \ No newline at end of file
>
> +Milestone 3 React Calculator
>
>
>
>    - [OPTIONAL] I'd strongly encourage you to update your README file to
>    the template linked by my colegues, the reason for that is that you'll most
>    likelly have to do that in the future in career/interview prep and that a
>    better README file can make recruiters more prone to contact you about jobs
>    and opportunities.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/em-em-D/React-calculator/pull/3#pullrequestreview-489048469>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJAWTVHJLNUSECZLOYN4F4TSF7H5VANCNFSM4QY3BL2A>
> .
>

2020-09-15 23:25 UTC, uryelah commented
@em-em-D I tested it in my machine and it seems to be possible to do the pointed fixes. 
Maybe there's a configuration issue going on in your local one.
You can schedule a call with a Fulltime TSE to get more help in solving this issue https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-.

2020-09-16 00:05 UTC, uryelah requested changes
Please reach out to a TSE, or even a teammate, to help you debug the code. 
It's always possible to fix bugs and issues!

2020-09-16 00:05 UTC, uryelah commented on src/components/App.js
> +          <ButtonPanel handleClick={this.handleClick} />
- [ ] Where is this.handleClick coming from? 
Make sure all the functions you are used are declared somewhere.

- [ ] App should be a functional component:
<img width="821" alt="appFunctionalComponent" src="https://user-images.githubusercontent.com/16193212/93276848-1739ae80-f797-11ea-9ec3-507be934544b.png">

2020-09-16 13:00 UTC, em-em-D commented
I am delighted to say that everything works perfectly well and all linters and style errors have passed

2020-09-16 16:32 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @em-em-D good job man, you have done really well to follow up with this and make sure it works properly, whoops that wasn't easy :slightly_smiling_face:  please merge and move on **This is approved** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-09-17 09:27 UTC, closed without merging

2020-09-17 09:27 UTC, em-em-D commented
milestone 3 done

2020-09-17 09:28 UTC, em-em-D commented
milestone 3 done and dusted