Featuremilestone4 branch
em-em-D/React-calculator pull request #4
Opened 2020-09-10 16:59 UTC by em-em-D

milestone 4 logic and requirement has been met and everything is fully functional

2020-09-10 18:46 UTC, Forison requested changes
## Status:: Changes required❌
# 🙋‍♂️ Michael
#### You have done a great job on this one so far, here are a few issues we have to address to have this project approved🤗.
* [ ] Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))
- Kindly enable linter checks on the repository.

That is it kindly make the changes and submit a re-review👷 .

#### Happy coding👨‍💻.

Addo Forison

2020-09-10 18:46 UTC, Forison commented on src/logical/operate.js
> +    if (number2 === undefined) return number1;
**[OPTIONAL]**
- I wonder the purpose of this line, but let see how it would turn out🤔 .

2020-09-10 18:46 UTC, Forison commented on src/logical/operate.js
> +    try{
**[OPTIONAL]**
- ```try and catch``` with ```switch```, isn't it an overkill? why not let the default method capture the error🤔 .

2020-09-16 13:01 UTC, em-em-D commented
I am delighted to say that everything works perfectly well and all linters and style errors have passed

2020-09-16 16:28 UTC, Oghenebrume50 approved these changes
### APPROVED

Hi @em-em-D good job working on this, kudos on making changes, please move on to the next milestone. **This is approved** :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-09-16 16:55 UTC, merged